/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List todos */
        get: operations["listTodos"];
        put?: never;
        /** Create a todo */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{todoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        /** Get a todo by id */
        get: operations["getTodo"];
        put?: never;
        post?: never;
        /** Delete a todo */
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @example 0.1.0 */
            version: string;
        };
        /**
         * @default all
         * @enum {string}
         */
        TodoStatus: "all" | "open" | "done";
        Todo: {
            /** Format: uuid */
            id: string;
            title: string;
            done: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        TodoList: {
            todos: components["schemas"]["Todo"][];
        };
        CreateTodoRequest: {
            title: string;
        };
        Error: {
            /** @example not_found */
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description An error occurred */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TodoId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listTodos: {
        parameters: {
            query?: {
                /** @description Filter by completion status */
                status?: components["schemas"]["TodoStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of todos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoRequest"];
            };
        };
        responses: {
            /** @description The created todo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested todo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The todo was deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
}
